### ISSUE TITLE
Context specific eQTL with no overlapping individuals

### ISSUE THREAD

**Issue by mariesaitou** [BrunildaBalliu/FastGxC#2]
Hello. Thank you for developing this great tool.
I was able to run this for the toy data, but I realized that I could not use this tool for my dataset as is because my data are animals raised in three conditions, and I do not have data for multiple conditions of the same individual.

They are genetically homogeneous populations that are divided into three separate groups. Is there any way to use this tool for such a data set? Or, do you know of a good tool for context-specific eQTL for non-overlapping individuals?

So far, I have tried [PICALO](https://github.com/molgenis/PICALO) but it did not work well in my environment.

I appreciate your help.

**Comment by BrunildaBalliu** [comment]
Hi Marie,

So glad you tried FastGxC!

Indeed, FastGxC is intended for cases where samples overlap across contexts
as it models the shared noise.

What is the exact test that you are interested in? Do you want to find
eQTLs with effect size heterogeneity in the three conditions? The extension
of FastGxC to the case of non-overlapping samples should be fairly trivial
(similar to an interaction test). Otherwise you can fit a genotype -
condition interaction model
Expression ~ a + b1 Genotype + b2 Condition + g1 Genotype x Condition

and test for the significance of g1 using a Wald test or LRT

Best,
Bruna

**Comment by mariesaitou** [comment]
Thank you very much for your prompt reply...! 
Yes, "find eQTLs with effect size heterogeneity in the three conditions" are what I am interested in. 
Such as below - this is just one example.

<img width="868" alt="Screenshot 2022-11-08 at 22 06 32" src="https://user-images.githubusercontent.com/41928205/200675609-c7359a56-d73a-455a-8d8e-e3739dd10a60.png">

**Comment by BrunildaBalliu** [comment]
In this case, I would run a genotype-by-condition interaction model
Expression ~ a + b1 Genotype + b2 Condition + g1 Genotype x Condition and
test for the significance of g1 using a likelihood ratio test. If g1
significantly differs from zero, the genetic effect differs between at
least one pair of your conditions. Does that make sense?

The other option is to run a meta-analysis test.

**Comment by mariesaitou** [comment]
Yes, I managed to make the model work on R for testing! Thanks a lot.
